<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\DotNetG2P.Core\DotNetG2P.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="LibNMeCab" Version="0.10.2" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
